class locators(object):
    EnterSomeValue = "com.code2lead.kwad:id/EnterValue"
    ContactUs = "com.code2lead.kwad:id/ContactUs"
    ScrollView = "com.code2lead.kwad:id/ScrollView"
    TabView = "com.code2lead.kwad:id/TabView"
    Zoom = "com.code2lead.kwad:id/Zoom"
    LoginMainScreen = "com.code2lead.kwad:id/Login"
    email = "com.code2lead.kwad:id/Et4"
    password = "com.code2lead.kwad:id/Et5"
    loginButton = "com.code2lead.kwad:id/Btn3"
    LongClick = "com.code2lead.kwad:id/LongClick"